import { ROLE } from '../constants/roleConstants';

export const sheetIds = {
  [ROLE.ADMIN]: process.env.NEXT_PUBLIC_SHEET_ID_ADMIN_SHEET,
  [ROLE.ADMIN_PRODUCTION]: process.env.NEXT_PUBLIC_SHEET_ID_PRODUCTION_SHEET,
  [ROLE.ADMIN_FINANCE]: process.env.NEXT_PUBLIC_SHEET_ID_FINANCE_SHEET,
  [ROLE.ADMIN_COMMERCE]: process.env.NEXT_PUBLIC_SHEET_ID_COMMERCE_SHEET,
  [ROLE.ADMIN_RRHH]: process.env.NEXT_PUBLIC_SHEET_ID_RRHH_SHEET,
  [ROLE.ADMIN_ADMIN]: process.env.NEXT_PUBLIC_SHEET_ID_ADMIN_SHEET,
  [ROLE.WORKER_WAREHOUSE]: process.env.NEXT_PUBLIC_SHEET_ID_WAREHOUSE_SHEET,
  [ROLE.WORKER_COMMERCE]: process.env.NEXT_PUBLIC_SHEET_ID_COMMERCE_SHEET,
  [ROLE.WORKER_QUALITY]: process.env.NEXT_PUBLIC_SHEET_ID_QUALITY_SHEET,
  [ROLE.WORKER_LABS]: process.env.NEXT_PUBLIC_SHEET_ID_LABS_SHEET,
  [ROLE.WORKER_LABS_MINERAL]: process.env.NEXT_PUBLIC_SHEET_ID_LABS_MINERAL_SHEET,
  [ROLE.WORKER_LABS_AR]: process.env.NEXT_PUBLIC_SHEET_ID_LABS_AR_SHEET,
  [ROLE.WORKER_MONTAGE]: process.env.NEXT_PUBLIC_SHEET_ID_MONTAGE_SHEET,
  [ROLE.WORKER_DISPATCH]: process.env.NEXT_PUBLIC_SHEET_ID_DISPATCH_SHEET,
  status: process.env.NEXT_PUBLIC_SHEET_ID_STATUS_SHEET,
  merma: process.env.NEXT_PUBLIC_SHEET_ID_MERMA_SHEET,
  garantia: process.env.NEXT_PUBLIC_SHEET_ID_WARRANTY_SHEET,
};